image: debian

before_script:
  - apt-get update
  - apt-get --yes --force-yes install rsync ssh wget jq

stages:
  - test
  - upload

test:
  stage: test
  script:
  - echo "Dummy line for now"
  - for file in *;
    do
      echo $file
    done

upload:
  stage: upload
  script:
  - echo "${SSH_PRIVATE_KEY}" > id_rsa
  - chmod 400 id_rsa
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - rsync -hrvz --delete --exclude='aerobear' --exclude='\..*' -e 'ssh -i id_rsa' ./ uav@tsunami.ocf.berkeley.edu:~/git-demo/
  only:
    refs:
    - master

after_script:
  - rm -rf "${HOME}/.ssh"
  - rm -rf id_rsa
