image: debian

before_script:
  - apt-get update
  - apt-get --yes --force-yes install rsync ssh wget jq

stages:
  - test
  - upload

test:
  stage: test
  script:
  - echo "Dummy line for now"
  - |
    for file in data/*;
    do
      cat $file | jq empty
    done

upload:
  stage: upload
  script:
  - echo "${SSH_PRIVATE_KEY}" > id_rsa
  - chmod 400 id_rsa
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - rsync -hrvz --delete --exclude='venv' --exclude='__pycache__' --exclude='\..*' -e 'ssh -i id_rsa' src/ uav@tsunami.ocf.berkeley.edu:~/git-demo/
  - rsync -hrvz --delete --exclude='venv' --exclude='__pycache__' --exclude='\..*' -e 'ssh -i id_rsa' data/ uav@tsunami.ocf.berkeley.edu:~/git-demo/data/
  only:
    refs:
    - master

after_script:
  - rm -rf "${HOME}/.ssh"
  - rm -rf id_rsa
